import './globals.css'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ImageProvider} from "@/context/imageContext"
import { AuthProvider } from '@/context/authContext'
import {PostProvider} from "@/context/postContext"

import {ReduxProvider} from "@/reduxProvider"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}){
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <AuthProvider>
          <PostProvider>
        <ImageProvider>
        {children}
        </ImageProvider>
        </PostProvider>
        </AuthProvider>
        </ReduxProvider>
        </body>
    </html>
  )
}
